import Head from 'next/head'
import About from '../components/About/About'
import Contact from '../components/Contact/Contact'
import Header from '../components/Header/Header'
import Home from '../components/Home/Home'
import Skills from '../components/Skills/Skills'
import Works from '../components/Works/Works'
import gsap from 'gsap/dist/gsap';
import ScrollToPlugin from 'gsap/dist/ScrollToPlugin';
import ScrollTrigger from 'gsap/dist/ScrollTrigger';
import { useEffect, useState } from 'react'
import { shuffle } from 'lodash'

gsap.registerPlugin(ScrollToPlugin, ScrollTrigger)

const colors = [
  "from-[#006466]",
  "from-[#272640]",
  "from-[#3e1f47]",
  "from-[#0f5132]",
  "from-[#264653]",
  "from-[#370617]",
  "from-purple-900",
]

export default function App({ data }) {
  const [color, setColor] = useState();

  useEffect(() => {
    setColor(shuffle(colors).pop());
  }, [])

  return (
    <div className={`overflow-x-hidden relative`} >
      <Head>
        <title>My Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Z.png" />
      </Head>
      <div className={`absolute w-full h-screen bg-gradient-to-b to-[#1A1A1A] ${color}`}>

      </div>
      <Header gsap={gsap}/>
      <Home gsap={gsap} color={color}  name={data.name} developer={data.developer} social_media={data.social_media}/>
      <About gsap={gsap} about={data.about}/>
      <Works gsap={gsap} works={data.works}/>
      <Skills data={data.skill}/>
      <Contact />
      <p className='text-center my-2 text-sm font-medium'>© Copyright 2017  Cuexx Developer</p>
    </div>
  )
}

export async function getStaticProps(context) {
  const data = require('../data');
  return {
    props: {
      data
    },
  }
}
